#!/bin/bash
#script by Abi Darwish

clear
echo " IP Hunter v2.1 by Abi Darwish"
echo
read -p "Have you turned off all VPNs? [y/n]: " VPNOFF
if [[ $VPNOFF == "y" ]]; then
    clear
    echo " IP Hunter v2.1 by Abi Darwish"
    echo
    until [[ $(curl -s ipv4.icanhazip.com | cut -d. -f1,2) == "113.211" ]]; do
    if [[ $(curl -s ipv4.icanhazip.com | cut -d. -f1,2) == "113.211" ]]; then
        clear
        echo " IP Hunter v2.1 by Abi Darwish"
        echo
        echo "Successfully connected to ${publicIP}"
        echo "You can turn on VPN now"
        exit 0
    fi
    echo "Start hunting..."
    sleep 1
    publicIP=$(curl -s ipv4.icanhazip.com)
    echo "Got ${publicIP}"
    sleep 1
    curl -s -o /dev/null http://192.168.8.1:8989/cgi-bin/changeip.cgi
    if [[ $? != 0 ]]; then
        echo
        echo "Error: your modem doesn't have AIO installed"
        echo
        exit 0
    fi
    echo "Hunting again in 15 seconds (press Ctrl+C to cancel)..."
    sleep 15
    echo
    done
else
    exit 0
fi
